user_provided_deployment_id: datarobot/brent.hinks/diabetes_sklearn_deployment
user_provided_model_id: datarobot/brent.hinks/diabetes_sklearn_model
prediction_environment_name: "https://datarobot-support.orm.datarobot.com"