user_provided_deployment_id: datarobot/brent.hinks/diabetes_sklearn_deployment_v3
user_provided_model_id: datarobot/brent.hinks/diabetes_sklearn_model_v3
prediction_environment_name: "https://datarobot-support.orm.datarobot.com"