user_provided_model_id: datarobot/brent.hinks/diabetes_sklearn_model_v2
target_type: Binary
settings:
  name: Custom Diabetes [GitHub Actions]
  target_name: readmitted
  description: Custom sklearn diabetes model
  language: Python
  negative_class_label: 'False'
  positive_class_label: 'True'
  training_dataset_id: 6123df824fd7c3eb7bb5e12d


version:
  # Make sure this is the environment ID is in your system.
  # This one is the '[DataRobot] Python 3 Scikit-Learn Drop-In' environment
  model_environment_id: 5e8c889607389fe0f466c72d

test:
  skip: false
  test_data_id: 6123df824fd7c3eb7bb5e12d
  checks:
    null_value_imputation:
      block_deployment_if_fails: false
      enabled: true
    performance:
      block_deployment_if_fails: false
      enabled: false
      max_execution_time: 100
      maximum_response_time: 50
      number_of_parallel_users: 3
    prediction_verification:
      block_deployment_if_fails: false
      enabled: false
      match_threshold: 0.9
      output_dataset_id: 6123df824fd7c3eb7bb5e12d
      passing_match_rate: 85
      predictions_column: readmitted
    side_effects:
      block_deployment_if_fails: false
      enabled: false
    stability:
      block_deployment_if_fails: false
      enabled: false
      maximum_payload_size: 1000
      minimum_payload_size: 100
      number_of_parallel_users: 1
      passing_rate: 95
      total_prediction_requests: 50