name: DataRobot Test and Deploy
permissions: write-all

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: pip install pandas numpy scikit-learn
    - name: Train model
      run: python ./train_model.py
    - name: Stage changed files
      run: git add .
    - name: Commit changed files
      run: git commit -m "Auto check-in serialized model"
    - name: fetch from main
      run: git fetch origin main
    - name: push code to main
      run: git push origin HEAD:main

  datarobot-custom-models:
    # Run this job on any action of a PR, but skip the job upon merging to the main branch. This
    # will be taken care of by the push event.
    needs: train
    if: ${{ github.event.pull_request.merged != true }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: DataRobot Custom Models Step
        id: datarobot-custom-models-step
        uses: datarobot-oss/custom-models-action@v1.1.8
        with:
          api-token: ${{ secrets.DATAROBOT_API_TOKEN }}
          webserver: https://app.datarobot.com/
          branch: main
          allow-model-deletion: true
          allow-deployment-deletion: true